version: "3.8"

services:
  inditex-service:
    image: ${DOCKERHUB_USER}/inditex-service:${IMAGE_TAG}
    container_name: inditex-service
    ports:
      - "${APP_PORT}:8080"
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
    restart: unless-stopped
